#Git action Workflow to automate push to ECR
name: Push to ECR


on: 
  push:
    branches: [ master ]
  
  #allows for manual execution
  workflow_dispatch:

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v3
      
      #Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1

    - name: App build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ecr_application
        IMAGE_TAG: app_image_v1
      run: 
          cd Application
          ls -ltra
          # Docker build
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Unit test
          docker run -d -p 8080:8080 --name my_app $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker ps
          echo "Pause for 10 seconds to let container start"
          sleep 10
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
    - name: MySQL DB build, test, tag, and push image to Amazon ECR
        env:
         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         ECR_REPOSITORY: db_repo
         IMAGE_TAG: v2.0
        run: 
          cd Application
          ls -ltra
          # Docker build
          docker build -f Dockerfile_mysql -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          # Unit test
          docker run -d -e MYSQL_ROOT_PASSWORD=db123 --name my_db $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker ps
          echo "Pause for 10 seconds to let container start"
          sleep 10
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          
        
